# Site settings
author: Young Hyun Kevin Kim
title: Why I Decided to Study Software Engineering
header-img: img/home-bg.png
email: kevinkim.yhk@gmail.com
copyright_name: Young Hyun Kevin Kim
description: > # this means to ignore newlines until "baseurl:"
  My path and decision to go down this career
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kevin-yhk

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
